export { default as MoviesList } from "./MoviesList";
export { default as LoadingGlobal } from "./LoadingGlobal";
export { default as MovieCard } from "./MovieCard";
export { default as MovieDescription } from "./MovieDescription";
export { default as Menu } from "./Menu";
export { default as PosterImg } from "./PosterImg";
export { default as Slider } from "./Slider/Slider";
export { default as SearchInput } from "./SearchInput";
export { default as Footer } from "./Footer";
